Repository DEFRA/waste-exemptions-front-office, pull requests merged in 2019-03, with the labels that each got.

#58 Unlock Rails version
  Gemfile
  Gemfile.lock
Labels: housekeeping

#62 Update schema with farmer columns, users and versions
  db/schema.rb
Labels: housekeeping

#65 Add assistance_mode to registration
  db/schema.rb
Labels: enhancement

#70 Fix Airbrake for the dev environment
  config/initializers/airbrake.rb
Labels: bug

#75 Update schema to include deregistered_on
  db/schema.rb
Labels: housekeeping
