Repository DEFRA/waste-exemptions-front-office, pull requests merged in 2019-09, with the labels that each got.

#221 Implement Accessibility Statement page
  app/views/pages/accessibility.html.erb
  app/views/shared/_footer.html.erb
Labels: enhancement

#225 Remove GMT from accessibility statement
  app/views/pages/accessibility.html.erb
Labels: enhancement

#226 Update schema following RUBY-580
  db/schema.rb
Labels: enhancement

#224 Initial API with dummy stats
  app/controllers/stats_controller.rb
  app/models/stats.rb
  config/routes.rb
  spec/models/stats_spec.rb
  spec/requests/stats_spec.rb
Labels: enhancement

#228 Calculate and display top stat 1
  app/models/stats.rb
  spec/factories/registration.rb
  spec/models/stats_spec.rb
Labels: enhancement

#230 Calculate and display top stat 2
  app/models/stats.rb
  spec/factories/registration.rb
  spec/models/stats_spec.rb
Labels: enhancement

#233 Calculate and display top stat 3
  app/models/stats.rb
  spec/models/stats_spec.rb
Labels: enhancement

#236 Update schema.rb
  db/schema.rb
Labels: housekeeping

#235 Stat 2 returns 0 if there are no registrations in the past week
  app/models/stats.rb
  spec/models/stats_spec.rb
Labels: bug

#241 Add style for button links
  app/assets/stylesheets/application.scss
  app/assets/stylesheets/partials/_links.scss
Labels: enhancement

#239 Top stat 3 to exclude back office renewals
  app/models/stats.rb
  spec/models/stats_spec.rb
Labels: bug

#242 Refactor stats
  app/controllers/stats_controller.rb
  app/models/stats.rb
  app/models/stats/assisted_registrations.rb
  app/models/stats/base_stat.rb
  app/models/stats/email_renewals.rb
  app/models/stats/new_registrations.rb
  app/models/stats/stats_formatter.rb
  spec/factories/registration.rb
  spec/models/stats/assisted_registrations_spec.rb
  spec/models/stats/base_stat_spec.rb
  spec/models/stats/email_renewals_spec.rb
  spec/models/stats/new_registrations_spec.rb
  spec/models/stats/stats_formatter_spec.rb
  spec/models/stats_spec.rb
Labels: enhancement, housekeeping

#252 Housekeeping on the env vars
  .env.example
  config/application.rb
  config/initializers/waste_exemptions_engine.rb
Labels: housekeeping
