Repository DEFRA/waste-exemptions-front-office, pull requests merged in 2019-02, with the labels that each got.

#20 Remove passenger from dev group in Gemfile
  Gemfile
Labels: housekeeping

#25 Fix test mailer and add specs
  app/mailers/test_mailer.rb
  app/views/test_mailer/test_email.text.erb
  config/initializers/waste_exemptions_engine.rb
  spec/mailers/test_mailer_spec.rb
Labels: bug

#23 Ensure input widths align with recommended GDS styles
  app/assets/stylesheets/application.scss
  app/assets/stylesheets/partials/_input.scss
Labels: enhancement

#31 Make use of airbrake configurable in initializer
  config/initializers/airbrake.rb
Labels: enhancement

#32 Align rspec test setup with WEX engine
  spec/rails_helper.rb
  spec/spec_helper.rb
  spec/support/database_cleaner.rb
  spec/support/factory_bot.rb
  spec/support/simplecov.rb
Labels: housekeeping

#33 Set secret_key_base when run under prod & rake
  config/application.rb
Labels: bug

#37 Add missing helper statement to application ctrllr
  app/controllers/application_controller.rb
Labels: bug

#36 Update the privacy policy content
  app/assets/stylesheets/application.scss
  app/assets/stylesheets/partials/_published_date.scss
  app/views/pages/privacy.html.erb
Labels: enhancement

#39 Add pgreset gem to solve database in use errors
  Gemfile
  Gemfile.lock
Labels: housekeeping

#40 Remove dummy secret key logic in application.rb
  config/application.rb
Labels: housekeeping
