Repository DEFRA/waste-exemptions-front-office, pull requests merged in 2019-04, with the labels that each got.

#77 Update to support last email cache feature
  Gemfile.lock
  config/initializers/waste_exemptions_engine.rb
  db/schema.rb
Labels: enhancement

#95 Add test coverage for correct handling of 404 errors.
  spec/requests/page_not_found_spec.rb
  spec/support/error_responses_helper.rb
Labels: bug

#98 Remove byebug and swap it with pry-byebug
  Gemfile
  Gemfile.lock
  spec/spec_helper.rb
Labels: housekeeping
