Repository DEFRA/waste-exemptions-front-office, pull requests merged in 2022-02, with the labels that each got.

#512 Bump brakeman
  .github/workflows/brakeman-analysis.yml
Labels: dependencies

#514 Fix db schema
  db/schema.rb
Labels: housekeeping

#515 Update privacy notice
  app/views/pages/privacy.html.erb
Labels: enhancement

#520 Privacy notice update webpage title
  app/views/pages/privacy.html.erb
Labels: enhancement

#521 Change in accessibility statement adding ‘Non-accessible content’ section
  Gemfile
  app/views/pages/accessibility.html.erb
Labels: enhancement
